"""schema inicial: pratos, ingredientes e alergenos

Revision ID: db750984929c
Revises: 
Create Date: 2026-09-28 20:32:57.925517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db750984929c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alergenos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('origem', sa.Enum('VEGETAL', 'ANIMAL', 'CARNE', name='origem'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('ingrediente_alergeno',
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('alergeno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alergeno_id'], ['alergenos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ingrediente_id', 'alergeno_id')
    )
    op.create_table('pratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('imagem', sa.String(length=200), nullable=True),
    sa.Column('imagem_alt', sa.String(length=300), nullable=True),
    sa.Column('picante', sa.Boolean(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pratos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pratos_categoria_id'), ['categoria_id'], unique=False)

    op.create_table('prato_ingrediente',
    sa.Column('prato_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prato_id'], ['pratos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prato_id', 'ingrediente_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prato_ingrediente')
    with op.batch_alter_table('pratos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pratos_categoria_id'))

    op.drop_table('pratos')
    op.drop_table('ingrediente_alergeno')
    op.drop_table('ingredientes')
    op.drop_table('categorias')
    op.drop_table('alergenos')
    # ### end Alembic commands ###
